import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import personaRoutes from './persona.routes';
import productoRoutes from './producto.routes';
import ubicacionRoutes from './ubicacion.routes';
import ventaRoutes from './venta.routes';
import terminalRoutes from './terminal.routes';
import cajaRoutes from './caja.routes';
import reporteRoutes from './reporte.routes';
import pedidoRoutes from './pedido.routes';
import pedidoInternoRoutes from './pedidoInterno.routes';
import deliveryRoutes from './delivery.routes';
import precobranzaRoutes from './precobranza.routes';
import comprasRoutes from './compras.routes';
import planillasRoutes from './planillas.routes'
import sectorRoutes from './sector.routes';
import remisionRoutes from './remision.routes';
import ajustesRoutes from './ajustes.routes';
import impuestoRoutes from './impuesto.routes';
import auditoriaRoutes from './auditoria.routes';
import rolRoutes from './rol.routes';
import usuarioRoutes from './usuario.routes';
import terminalWebRoutes from './terminalWeb.routes';
import stockInicialRoutes from './stockInicial.routes';
import denominacionRoutes from './denominacion.routes';
import anulacionRoutes from './anulacion.routes';
import consultaVentaRoutes from './consultaVenta.routes';
import consultaArqueoRoutes from './consultaArqueo.routes';
import ofertaRoutes from './oferta.routes';
import cargaProductosRoutes from './cargaProductos.routes';
import barcodeRoutes from './barcode.routes';
import consultaCargaProductosRoutes from './consultaCargaProductos.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/persona', personaRoutes);
router.use('/producto', productoRoutes);
router.use('/caja', cajaRoutes);
router.use('/ubicaciones', ubicacionRoutes);
router.use('/venta', ventaRoutes);
router.use('/pedido', pedidoRoutes);
router.use('/reporte', reporteRoutes);
router.use('/terminal', terminalRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/denominacion', denominacionRoutes);
router.use('/precobranza', precobranzaRoutes);
router.use('/compras', comprasRoutes);
router.use('/remisiones', remisionRoutes);
router.use('/pedido-interno', pedidoInternoRoutes);
router.use('/planillas', planillasRoutes);
router.use('/sector', sectorRoutes);
router.use('/ajustes', ajustesRoutes);
router.use('/impuesto', impuestoRoutes);
router.use('/auditoria', auditoriaRoutes);
router.use('/rol', rolRoutes);
router.use('/usuario', usuarioRoutes);
router.use('/terminal-web', terminalWebRoutes);
router.use('/stock-inicial', stockInicialRoutes);
router.use('/anulacion', anulacionRoutes);
router.use('/consulta-venta', consultaVentaRoutes);
router.use('/consulta-arqueo', consultaArqueoRoutes);
router.use('/ofertas', ofertaRoutes);
router.use('/carga-productos', cargaProductosRoutes);
router.use('/barcode', barcodeRoutes);
router.use('/consulta-carga-productos', consultaCargaProductosRoutes);

export default router;